log_dir: "/usr/local/projdata/0372/projects/MTG4/MedicMineData/download_logs"
data_dir: "/usr/local/projdata/0372/projects/MTG4/MedicMineData/"

default_sources:
  - "GOAnnotation"
  - "InterPro"
  - "InterProGO"
  - "NCBIGene"
  - "PubMed"
  - "UniProt"

UniProt:
    organisms:
        - 3880
