log_dir: "/usr/local/projects/MTG4/medicmine/log/download_logs"
data_dir: "/usr/local/projects/MTG4/medicmine/complete/go_annotation/"

default_sources:
  - "GOAnnotation"
  - "IntAct"
  - "IntActVocabulary"
  - "InterPro"
  - "InterProGO"
  - "NCBIGene"
  - "PubMed"
  - "UniProt"

UniProt:
    organisms:
        - 3880
